AWSTemplateFormatVersion: "2019-09-09"
Transform: AWS::Serverless-2016-10-31
Description: API de envios
Resources:
  Envios:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 60
      Events:
        NuevoEnvio:
          Type: Api
          Properties:
            Path: /envios
            Method: post
        EnvioId:
          Type: Api
          Properties:
            Path: /envios/pendientes
            Method: get
        EnviosPendiendtes:
          Type: Api
          Properties:
            Path: /envios/{id}
            Method: get
        EnvioEntregado:
          Type: Api
          Properties:
            Path: /envios/{id}/entregado
            Method: post
        